name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          select: "E,F"
          exclude: ".git,__pycache__,__init__.py,__manifest__.py"
          max-line-length: "88"
          path: "."
          plugins: "flake8-bugbear==22.1.11 flake8-black"
