name: Example
on:
  pull_request:
    branches: ["main"]

jobs:
  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Comment the results on the PR
        uses: Libra-foundation/radon-comment@V1.0
        with:
          src: "."
          min: "A"
          grade: "B"
